- name: setup prompt
  ansible.builtin.shell: set-prompt github-runner

- name: add github runner user
  ansible.builtin.user:
    name: grunner

- name: Create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner


- name: Extract and download runners
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.319.0/actions-runner-linux-x64-2.319.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
    owner: grunner
    group: grunner

- name: Grab Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/DevOps-projects-24/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-user # Token can be fetched by ec2-user as gh login was done by that user.

- name: print token
  ansible.builtin.debug:
    msg: "{{ token }}"

#- name: download github cli repo
#  ansible.builtin.get_url:
#    url: https://cli.github.com/packages/rpm/gh-cli.repo
#    dest: /etc/yum.repos.d/gh-cli.repo
#
#- name: install github cli
#  ansible.builtin.dnf:
#    name: gh-cli
#    state: latest


- name: Install libicu dependency
  ansible.builtin.dnf:
    name: libicu
    state: latest

- name: Get the runner count
  ansible.builtin.shell: |
    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/raghudevopsb80/actions/runners | jq .total_count |xargs
  register: runner_count
  become_user: ec2-user

- name: Configure Github Runner
  ansible.builtin.shell: ./config.sh --url https://github.com/DevOps-projects-24 --token {{ token.stdout }} --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become_user: grunner
  when: runner_count.stdout == "0" or runner_status.stdout == "offline"

- name: Install Runner Service
  ansible.builtin.shell: ./svc.sh install grunner ;  ./svc.sh start
  args:
    chdir: /actions-runner
  when: runner_count.stdout == "0"

- name: Download Terraform Repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: latest